version: '3.9'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    container_name: my_timescaledb
    environment:
      POSTGRES_PASSWORD: Aj189628@
      POSTGRES_USER: dev
      POSTGRES_DB: nest-ecom
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: my_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Aj189628@
      MYSQL_DATABASE: nest-ecom
      MYSQL_USER: dev
      MYSQL_PASSWORD: Aj189628@
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass Aj189628@"]

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Aj189628@

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: Aj189628@
  #     ME_CONFIG_MONGODB_URL: mongodb://root:Aj189628@@mongo:27017/

volumes:
  timescaledb_data:
    driver: local
  mysql_data:
    driver: local
  redis_data:
    driver: local